apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-deployment
  template:
    metadata:
      labels:
        app: job-deployment
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-job-service:dev-e11689e
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: job-configmap
