apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-applyhub-app
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: 'https://github.com/applyhub7/applyhub-manifests'
    targetRevision: dev
    path: argocd-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
