apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-dev
  namespace: argocd
spec:
  project: dev
  sources:
    - repoURL: https://github.com/applyhub7/applyhub-manifests
      targetRevision: main
      path: apps-manifests/applyhub
      helm:
        releaseName: auth-service
        valueFiles:
          - $values/apps-manifests/env/dev/auth-service.yaml
    - repoURL: https://github.com/applyhub7/applyhub-manifests
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
