apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-deploy
  template:
    metadata:
      labels:
        app: application-deploy
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-application-service:b64f9ce
          ports:
            - containerPort: 4003
          envFrom:
            - configMapRef:
                name: application-cm
