{{- if .Values.externalsecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalsecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalsecret.secretStoreRef.name }}
    kind: {{ .Values.externalsecret.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-sec
    creationPolicy: {{ .Values.externalsecret.target.creationPolicy }}
  data:
    {{- range .Values.externalsecret.properties }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalsecret.remoteKey }}
        property: {{ . }}
    {{- end }}
{{- end }}