apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deploy
  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-frontend:6f5f30c
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-cm
