apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: api-gateway=docker.io/noseyug/applyhub-api-gateway-service
    argocd-image-updater.argoproj.io/api-gateway-service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/api-gateway.write-back-target: git:secret:argocd/git-creds
spec:
  project: default
  source:
    repoURL: 'https://github.com/applyhub7/applyhub-manifests'
    targetRevision: dev
    path: apps-manifests/api-gateway
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
