apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: job-service=docker.io/noseyug/applyhub-job-service
    argocd-image-updater.argoproj.io/job-service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/auth-service.manifest-path: job-deploy.yml
    argocd-image-updater.argoproj.io/job-service.write-back-target: git:secret:argocd/git-creds
spec:
  project: default
  source:
    repoURL: 'https://github.com/applyhub7/applyhub-manifests'
    targetRevision: dev
    path: apps-manifests/job-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
