apiVersion: v1
kind: ConfigMap
metadata:
  name: application-service-postgres-cm
  namespace: databases
  labels:
    app: application-service-postgres
    tier: database
data:
  POSTGRES_DB: "applyhub"