apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-deploy
  template:
    metadata:
      labels:
        app: job-deploy
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-job-service:38fa513
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: job-cm
