apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev-ci
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: noseyug@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-sec
              key: api-token
