apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-minio-sts
spec:
  serviceName: "application-minio-svc"
  replicas: 1
  selector:
    matchLabels:
      app: application-minio-sts
  template:
    metadata:
      labels:
        app: application-minio-sts
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: application-cm
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                 name: application-cm
                 key: MINIO_SECRET_KEY
          volumeMounts:
            - name: pgdata
              mountPath: /data

  volumeClaimTemplates:
   - metadata:
       name: pgdata
     spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
