apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgres-sts
spec:
  serviceName: "auth-postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres-sts
  template:
    metadata:
      labels:
        app: auth-postgres-sts
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: AUTH_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: AUTH_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: auth-cm
                  key: AUTH_DB_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
   - metadata:
       name: pgdata
     spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
