apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-cm
data:
  NODE_ENV: "production"
  GATEWAY_PORT: "4000"
  AUTH_URL: "http://auth-service:4001"
  JOB_URL: "http://job-service:4002"
  APPLICATION_URL: "http://application-service:4003"
