replicaCount: 2
image:
  name: noseyug/applyhub-application-service
  tag: "v0.0.1"
container:
  port: 4003
configmap:
  enabled: true
  data:
    NODE_ENV: "production"
    APPLICATION_PORT: "4003"
    APPLICATION_DB_HOST: "applyhub-db.crwsegu2uf4l.ap-southeast-1.rds.amazonaws.com"
    APPLICATION_DB_PORT: "5432"
    APPLICATION_DB_NAME: "application_service"
    MINIO_ENDPOINT: "s3.ap-southeast-1.amazonaws.com"
    MINIO_PORT: "443"
    MINIO_USE_SSL: "true"
    MINIO_BUCKET: "applyhub-bucket"
    MINIO_REGION: "ap-southeast-1"
externalsecret:
  enabled: true
  secretStoreRef:
    name: aws-sm-css
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  refreshInterval: 1h
  remoteKey: prod/applyhub/application-service
  properties:
    - APPLICATION_DB_USER
    - APPLICATION_DB_PASSWORD
    - MINIO_ACCESS_KEY
    - MINIO_SECRET_KEY
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuTargetUtilization: 70
  memoryTargetUtilization: 70
pdb:
  enabled: true
  minAvailable: 1
