apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-cm
data:
  NODE_ENV: "production"
  AUTH_PORT: "4001"
  AUTH_DB_HOST: "auth-postgres-svc"
  AUTH_DB_PORT: "5432"
  AUTH_DB_NAME: "applyhub"
  AUTH_DB_USER: "applyhub"
  AUTH_DB_PASSWORD: "applyhub"
  JWT_SECRET: "applyhubapplyhub"
