apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deploy
  template:
    metadata:
      labels:
        app: auth-deploy
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-auth-service:fdee975
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: auth-cm
