apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-deploy
  template:
    metadata:
      labels:
        app: api-gateway-deploy
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-api-gateway:99dc67c
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: api-gateway-cm
