apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
        - name: backend
          image: noseyug/applyhub-auth-service:dev-e11689e
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: auth-configmap
